// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmpD9km_AO9FsciPoGBF8S3dOh4gAdebw',
    appId: '1:758087066623:web:c2bd259deea0936a89fdca',
    messagingSenderId: '758087066623',
    projectId: 'chat-bot-38c8e',
    authDomain: 'chat-bot-38c8e.firebaseapp.com',
    storageBucket: 'chat-bot-38c8e.firebasestorage.app',
    measurementId: 'G-8H6P14PT2E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgiwBDcNgRwGGySRJTExXqXprFII0DiMg',
    appId: '1:758087066623:android:4fb254baf2a8fd3089fdca',
    messagingSenderId: '758087066623',
    projectId: 'chat-bot-38c8e',
    storageBucket: 'chat-bot-38c8e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFNjISJy-UiLOVNNCntn1c5SfH3LCD_-4',
    appId: '1:758087066623:ios:d4974efe3988ffa489fdca',
    messagingSenderId: '758087066623',
    projectId: 'chat-bot-38c8e',
    storageBucket: 'chat-bot-38c8e.firebasestorage.app',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFNjISJy-UiLOVNNCntn1c5SfH3LCD_-4',
    appId: '1:758087066623:ios:d4974efe3988ffa489fdca',
    messagingSenderId: '758087066623',
    projectId: 'chat-bot-38c8e',
    storageBucket: 'chat-bot-38c8e.firebasestorage.app',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBLmmesVxiXjv2xXKbXxmqd0GLIYiPLSI',
    appId: '1:758087066623:web:d278a664fa13167f89fdca',
    messagingSenderId: '758087066623',
    projectId: 'chat-bot-38c8e',
    authDomain: 'chat-bot-38c8e.firebaseapp.com',
    storageBucket: 'chat-bot-38c8e.firebasestorage.app',
    measurementId: 'G-RYPRWNKMC0',
  );
}
